export const DEFAULT_CATEGORIES = [
  { name: 'Hành động', slug: 'hanh-dong' },
  { name: 'Tình cảm', slug: 'tinh-cam' },
  { name: 'Hài hước', slug: 'hai-huoc' },
  { name: 'Phiêu lưu', slug: 'phieu-luu' },
  { name: 'Kinh dị', slug: 'kinh-di' },
  { name: 'Học đường', slug: 'hoc-duong' },
  { name: 'Fantasy', slug: 'fantasy' },
  { name: 'Sci-fi', slug: 'sci-fi' },
  { name: 'Slice of Life', slug: 'slice-of-life' },
  { name: 'Thể thao', slug: 'the-thao' },
  { name: 'Trinh thám', slug: 'trinh-tham' },
  { name: 'Lịch sử', slug: 'lich-su' },
  { name: 'Võ thuật', slug: 'vo-thuat' },
  { name: 'Drama', slug: 'drama' },
  { name: 'Siêu nhiên', slug: 'sieu-nhien' },
  { name: 'Chuyển sinh', slug: 'chuyen-sinh' },
  { name: 'Hệ thống', slug: 'he-thong' },
  { name: 'Ngôn tình', slug: 'ngon-tinh' },
  { name: 'Đam mỹ', slug: 'dam-my' },
  { name: 'Manga', slug: 'manga' },
  { name: 'Manhua', slug: 'manhua' },
  { name: 'Manhwa', slug: 'manhwa' },
] as const;
